/**
 * @class CANNON.ContactPoint
 * @brief A contact point between two bodies.
 * @description Should be generated by the ContactGenerator.
 * @param CANNON.Body bi
 * @param CANNON.Body bj
 */
CANNON.ContactPoint = function(bi, bj, normalConstraint, contactMaterial, tangentConstraint1, tangentConstraint2){
    this.bi = bi;
    this.bj = bj;
    this.n = normalConstraint;
    this.t1 = tangentConstraint1;
    this.t2 = tangentConstraint2;
    this.contactMaterial = contactMaterial;
};